# Project information
site_title: "Documentation | Textile"
site_name: "Documentation"
site_description: "Textile makes it easy for you or your application to store and distribute data over the IPFS network."
site_author: textile.io
site_url: https://docs.textile.io/

# Repository
repo_name: textileio/docs
repo_url: https://github.com/textileio/docs

# Copyright
copyright: "&copy; Textile"

# Configuration
theme:
  name: null
  custom_dir: material
  language: en
  feature:
    tabs: false
  palette:
    primary: default
    accent: default
  font:
    text: Roboto
    code: Roboto Mono
  favicon: images/favicon.ico
  logo: images/hex.svg
  static_templates:
    - 404.html

extra_javascript:
  - js/sidebar.js

extra_css:
  - css/textile.css

# Plugins
plugins:
  - search
  - codeyaml

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.attr_list
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: textileio
      repo: docs
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - markdown_captions

nav:
  - Home: index.md
  - The Hub:
      - Introduction: hub/introduction.md
      - Accounts: hub/accounts.md
      - Buckets: hub/buckets.md
      - App APIs: hub/app-apis.md
      - CLI Docs: hub/cli/tt.md
  - ThreadsDB:
      - Introduction: threads/introduction.md
      - Links:
          - JavaScript: https://textileio.github.io/js-threads
          - Golang: https://godoc.org/github.com/textileio/go-threads
          - Dart: https://textileio.github.io/dart-threads-client
  - Filecoin Powergate:
      - Introduction: powergate/introduction.md
      - Powergate: https://github.com/textileio/powergate/#powergate
  - Hub CLI:
      - Login: hub/cli/tt_login.md
      - Logout: hub/cli/tt_logout.md
      - Whoami: hub/cli/tt_whoami.md
      - Orgs: hub/cli/tt_orgs.md
      - Bucket: hub/cli/tt_bucket.md
      - Threads: hub/cli/tt_threads.md
      - API Keys: hub/cli/tt_keys.md
  - Resources:
      - ThreadsDB:
          - Links:
              - React App: https://github.com/textileio/js-examples/tree/master/react-todo
              - 3Box Identities: https://github.com/textileio/js-examples/tree/master/react-3box-threadsdb
              - React Native App: https://github.com/textileio/js-examples/tree/master/react-native-client-app
      - Buckets:
          - Website Hosting: tutorials/static-websites.md
          - Links:
              - 3Box User Buckets: https://github.com/textileio/js-examples/tree/master/react-3box-threadsdb

# Customization
extra:
  social:
    - type: globe
      link: https://textile.io
    - type: github-alt
      link: https://github.com/textileio
    - type: twitter
      link: https://twitter.com/textileio
    - type: medium
      link: https://blog.textile.io/
    - type: slack
      link: https://slack.textile.io
  go_textile:
    - version: v0.1.11
  yamls:
    - name: a_tour_of_textile
      yaml: snippets/a_tour_of_textile
